In [18]:
# settings local:
# run "../../../common/0_notebooks_base_setup.py"   

---

<img src='../../../common/logo_DH.png' align='left' width=35%/>


En la práctica de la clase de hoy usaremos un dataset de Kaggle que tiene datos de ventas:

https://www.kaggle.com/kyanyoga/sample-sales-data

Ustedes tienen un subconjunto de los datos disponibles, que usaremos para resolver ejercicios de Numpy.

## Ejercicio 1

Leer los datos del archivo /M1/CLASE_03_Numpy/Data/sales_data_sample_excercise.csv

Este archivo tiene algunos datos numéricos y otros de tipo cadena de caracteres. 

Las columnas son:

* ORDERNUMBER: int, id de la orden

* SALES: float, monto abonado

* MONTH_ID: int, mes

* YEAR_ID: int, año

* PRODUCTLINE: str, producto

* COUNTRY: str, país de venta

¿Recuerdan que todos los elementos de una instancia de ndarray deben ser del mismo tipo? Entonces vamos a leer el archivo y crear una instancia de ndarray de tipo cadena de caracteres.

¿Qué pasaría si intentáramos crear una instancia de tipo int? ¿Y de tipo float?


In [19]:
## [BORRAR_PRESENCIAL]

import numpy as np

# local:
data_location = '../Data/sales_data_sample_excercise.csv'

data = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= str)
data

array([['10107', '2871', '2', '2003', 'Motorcycles', 'USA'],
       ['10121', '2765.9', '5', '2003', 'Motorcycles', 'France'],
       ['10134', '3884.34', '7', '2003', 'Motorcycles', 'France'],
       ...,
       ['10386', '5417.57', '3', '2005', 'Ships', 'Spain'],
       ['10397', '2116.16', '3', '2005', 'Ships', 'France'],
       ['10414', '3079.44', '5', '2005', 'Ships', 'USA']], dtype='<U16')

## Ejercicio 2

Crear un array numérico que tenga como valores las columna SALES y otro array de str que tenga como valores la columna COUNTRY

Ayuda: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

In [20]:
## [BORRAR_PRESENCIAL]

sales_vector_str = data[:, 1]
sales_vector =  sales_vector_str.astype(np.float)
print(sales_vector)

country_vector = data[:, 5]
print(country_vector)


[2871.   2765.9  3884.34 ... 5417.57 2116.16 3079.44]
['USA' 'France' 'France' ... 'Spain' 'France' 'USA']


## Ejercicio 3

¿Cuál fue el monto mínimo de una venta? ¿Cuál fue el monto máximo?

In [21]:
## [BORRAR_PRESENCIAL]

monto_min = sales_vector.min()
monto_max = sales_vector.max()
print(monto_min)
print(monto_max)

482.13
14082.8


## Ejercicio 4

¿Cuántas ventas se hicieron en Spain?

Ayuda: boolean indexing


In [22]:
## [BORRAR_PRESENCIAL]

ventas_spain_mask = country_vector == 'Spain'
print(ventas_spain_mask)
ventas_spain = country_vector[ventas_spain_mask]
cant_ventas_spain = ventas_spain.size
cant_ventas_spain

[False False False ...  True False False]


342

## Ejercicio 5

¿Qué porcentaje de las ventas se hicieron en Spain?


In [23]:
## [BORRAR_PRESENCIAL]

cant_ventas_total = country_vector.size
porc_spain = 100* cant_ventas_spain / cant_ventas_total
porc_spain

12.114771519659936

## Ejercicio 6

¿Cuál es el país de la venta de precio máximo? ¿Cuál es el id de esa venta?

Ayuda: boolean indexing

In [24]:
## [BORRAR_PRESENCIAL]

print(data)
precio_max = sales_vector.max()
#print(precio_max)
precio_max_mask = sales_vector == precio_max
#print(precio_max_mask)
pais_max_precio = country_vector[precio_max_mask][0]
print(pais_max_precio)

id_vector_str = data[:, 0]
id_vector =  id_vector_str.astype(np.int)
id_max_precio = id_vector[precio_max_mask][0]
print(id_max_precio)

[['10107' '2871' '2' '2003' 'Motorcycles' 'USA']
 ['10121' '2765.9' '5' '2003' 'Motorcycles' 'France']
 ['10134' '3884.34' '7' '2003' 'Motorcycles' 'France']
 ...
 ['10386' '5417.57' '3' '2005' 'Ships' 'Spain']
 ['10397' '2116.16' '3' '2005' 'Ships' 'France']
 ['10414' '3079.44' '5' '2005' 'Ships' 'USA']]
USA
10407


## Ejercicio 7

¿Cuál es el precio promedio de ventas en France? ¿Cuál es el desvío?

In [25]:
## [BORRAR_PRESENCIAL]

ventas_france_mask = country_vector == 'France'
precios_france = sales_vector[ventas_france_mask]

promedio_france = precios_france.mean()
print(promedio_france)
desvio_france = precios_france.std()
print(desvio_france)

3537.9507006369427
1939.214360481481


## Ejercicio 8

¿Cuál fue el año con máximo desvío en las ventas en France?

Ayuda: https://docs.scipy.org/doc/numpy/reference/generated/numpy.unique.html

In [27]:

data_france_mask = country_vector == 'France'
data_france_sales = data[data_france_mask, 1]
data_france_years = data[data_france_mask, 3]

data_france_years_num = data_france_years.astype(np.int)

years_unique = np.unique(data_france_years_num)
print(years_unique)

desvios = []
for year in years_unique:
    years_vector_mask = data_france_years_num == year
    precios_year_mask = data_france_sales[years_vector_mask].astype(np.float)    
    desvio_year = precios_year_mask.std()
    desvios.append(desvio_year)

print(desvios)

desvio_max = np.array(desvios).max()
desvios_max_mask = desvios == desvio_max
year_desvio_max = years_unique[desvios_max_mask][0]
print(year_desvio_max)
    

[2003 2004 2005]
[1860.7718844747073, 1837.8438485766644, 2241.7723043613423]
2005


In [28]:
data_france_mask = country_vector == 'France'
data_france_sales, data_france_years = data[data_france_mask, 1], data[data_france_mask, 3]

years_unique = np.unique(data_france_years.astype(np.int))
print(years_unique)

desvios = np.std(data_france_sales.astype(np.float), axis=0)
print(desvios, type(desvios))
print(np.argmax(desvios))
year_desvio_max = years_unique[np.argmax(desvios)]
print(year_desvio_max)

[2003 2004 2005]
1939.214360481481 <class 'numpy.float64'>
0
2003


In [ ]:
a = np.arange(15)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])