In [1]:
# initial setup
%run "../../../common/0_notebooks_base_setup.py"


/media/paulati/Nuevo vol/paula/dh/2021/dsad_2021/common
default checking
Running command `conda list`... ok
jupyterlab=2.2.6 already installed
pandas=1.1.5 already installed
bokeh=2.2.3 already installed
seaborn=0.11.0 already installed
matplotlib=3.3.2 already installed
ipywidgets=7.5.1 already installed
pytest=6.2.1 already installed
chardet=4.0.0 already installed
psutil=5.7.2 already installed
scipy=1.5.2 already installed
statsmodels=0.12.1 already installed
scikit-learn=0.23.2 already installed
xlrd=2.0.1 already installed
Running command `conda install --yes nltk=3.5.0`... ok
Solving environment: ...working... done

# All requested packages already installed.


unidecode=1.1.1 already installed
pydotplus=2.0.2 already installed
pandas-datareader=0.9.0 already installed
flask=1.1.2 already installed


<link rel="stylesheet" href="../../../common/dhds.css">
<div class="Table">
    <div class="Row">
        <div class="Cell grey left"> <img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M1/CLASE_03_Numpy/Presentacion/img/M1_CLASE_03_portada.png" align="center" /></div>
        <div class="Cell right">
            <div class="div-logo"><img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/common/logo_DH.png" align="center" width=70% /></div>
            <div class="div-curso">DATA SCIENCE</div>
            <div class="div-modulo">MÓDULO 1</div>
            <div class="div-contenido">Numpy</div>
        </div>
    </div>
</div>

### Objetivos de la clase

- Manipulación de datos con Arrays de NumPy

- Vectorización de operaciones y optimización

- Acceso eficiente a los datos

<div class="div-dhds-fondo-1"> NumPy
<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M1/CLASE_03_Numpy/Presentacion/img/M1_CLASE_03_separador.png" align="center"></img>    
</div>


### ¿Qué es NumPy? 

---

<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M1/CLASE_03_Numpy/Presentacion/img/M1_CLASE_03_logo_numpy.png" align="center" width=15% />


NumPy es el paquete fundamental para la computación científica con Python. 

Contiene, entre otras cosas:

* Un poderoso elemento: los arrays de N-dimensiones (ND arrays)

* Funciones para realizar cálculos y operaciones matemáticas con arrays de forma muy eficiente (vectorización)

* Operaciones de álgebra lineal, generación de números aleatorios, entre otras funcionalidades de computación científica 

Esto permite que NumPy se integre de manera rápida y sin problemas con una amplia variedad de bases de datos.


### ¿Por qué utilizar arrays?

---

Un array es una **colección de items de datos**, llamados elementos, asociados a un único nombre de variable. 

Diseñados para:

* Facilitar la programación y proveer **buena performance**

* Almacenar y manipular **grandes colecciones de datos**

* Simplificar la tarea de nombrar y referenciar items individuales en una colección de datos

* Permitir la manipulación de una colección entera de datos con una simple sentencia


### ¿Qué es un array?

---

Un **array** es una estructura de datos que permite agrupar varios valores bajo un único nombre. 

**Los elementos de un array son todos del mismo tipo** (a diferencia de las listas de Python).

<div class="Table">
    <div class="Row Clase03">
        <div class="Cell"><img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M1/CLASE_03_Numpy/Presentacion/img/M1_CLASE_03_numpy_ndim.jpg" align="center" width=90% /></div>
        <div class="Cell Clase03 right">
            <ul>
                <li class ="li Clase03">Un vector es un arreglo unidimensional</li>                
                <li class ="li Clase03">Una tabla o matriz es un arreglo bidimensional</li>                
                <li class ="li Clase03">Por último un arreglo puede tener N dimensiones</li>
             <ul>
        </div>
    </div>
</div>

### Creación

---

La forma más sencilla de construir un array es usando el constructor con un único parámetro:

`numpy.array(object)`

donde object es una colección de elementos


In [2]:
import numpy as np

# Lista de python
python_list = [1, 4, 2, 5, 3]

# Arreglo (array) de enteros instanciado a partir de una lista:
my_numpy_array = np.array(python_list)

# Imprimo el numpy array creado
print(my_numpy_array)

[1 4 2 5 3]


### Acceso

---

Los arreglos se indexan desde 0 hasta len(a) - 1

<code>a[0]</code> devuelve el valor de la primera posición del arreglo

<code>a[len(a)-1]</code> devuelve el valor de la última posición del arreglo


In [3]:
my_numpy_array

array([1, 4, 2, 5, 3])

In [4]:
# primer elemento
my_numpy_array[0]

1

In [5]:
# cuarto elemento
my_numpy_array[3]

5

In [6]:
# último elemento
my_numpy_array[len(my_numpy_array)-1]

3

### Selección de elementos: indexing & slicing

---

<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M1/CLASE_03_Numpy/Presentacion/img/M1_CLASE_03_numpy_indexing.jpg" align="center" width=40% />

### Tipos de indexing

---

Llamamos “indexing” al proceso de acceder a los elementos de un array con algún criterio. 

Existen tres tipos de indexing en Numpy:

* **Slicing**: cuando accedemos a los elementos con los parámetros start,stop,step: <code>my_array[0:5:-1]</code>

* **Fancy Indexing**: Cuando creamos una lista de índices y la usamos para acceder a ciertos elementos del array: <code>my_array[[3,5,7,8]]</code>

* **Boolean Indexing**: Cuando creamos una “máscara booleana” (un array o lista de True y False) para acceder a ciertos elementos: <code>my_array[my_array > 4]</code>


#### Tipos de indexing - Slicing
---

https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html


In [7]:
one_d_array = np.arange(10)
one_d_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Start = 1:  empezamos por el segundo elemento
# Stop: No está definido, entonces llegamos hasta el final.
# Step: El paso o distancia entre los elementos es 2.
one_d_array[1::2]  

array([1, 3, 5, 7, 9])

In [9]:
# Start: No está definido, entonces comenzamos desde el primero.
# Stop: No está definido, entonces llegamos hasta el final.
# Step = -1, para invertir el orden del array
one_d_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Tipos de indexing - Fancy Indexing
---


In [10]:
low = 0 #incluye el limite inferior
high = 10 # no incluye el límite superior
size = (3, 4) # 3 filas y 4 columnas
random_generator_seed = np.random.default_rng()
two_d_array = random_generator_seed.uniform(low, high, size)
two_d_array

array([[1.67190734, 0.93429072, 6.7251717 , 3.91512176],
       [0.12807806, 6.62692054, 5.76450967, 1.39303695],
       [0.42202522, 3.04658696, 7.9725107 , 6.69451886]])

In [11]:
# nos quedamos con todas las columnas y las filas 1, 3, 2 y repetimos la 1 (índices 0,2,1,0)
lista_indices_filas = [0, 2, 1, 0]
two_d_array[lista_indices_filas]

array([[1.67190734, 0.93429072, 6.7251717 , 3.91512176],
       [0.42202522, 3.04658696, 7.9725107 , 6.69451886],
       [0.12807806, 6.62692054, 5.76450967, 1.39303695],
       [1.67190734, 0.93429072, 6.7251717 , 3.91512176]])

In [12]:
# nos quedamos con todas las filas y las columnas 3, 4, 2, y reptimos la 3 (índices 2,3,1,2)
lista_indices_columnas = [2, 3, 1, 2]
two_d_array[:, lista_indices_columnas]

array([[6.7251717 , 3.91512176, 0.93429072, 6.7251717 ],
       [5.76450967, 1.39303695, 6.62692054, 5.76450967],
       [7.9725107 , 6.69451886, 3.04658696, 7.9725107 ]])

#### Tipos de indexing - Boolean Indexing
---


In [13]:
one_d_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
mask_pair_number = one_d_array % 2 == 0
mask_pair_number

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [15]:
one_d_array[mask_pair_number]

array([0, 2, 4, 6, 8])

#### Tipos de indexing - Boolean Indexing (cont.)
---


In [16]:
mask_great_5 = two_d_array > 5
mask_great_5

array([[False, False,  True, False],
       [False,  True,  True, False],
       [False, False,  True,  True]])

In [17]:
two_d_array

array([[1.67190734, 0.93429072, 6.7251717 , 3.91512176],
       [0.12807806, 6.62692054, 5.76450967, 1.39303695],
       [0.42202522, 3.04658696, 7.9725107 , 6.69451886]])

In [18]:
two_d_array[mask_great_5]

array([6.7251717 , 6.62692054, 5.76450967, 7.9725107 , 6.69451886])

### Vectorización

---

Los Arrays de NumPy son estructuras mucho más eficientes para operar sobre los datos que las listas de Python. 

Esto en parte se debe a que en un NumPy Array el tipo de datos es fijo.

<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M1/CLASE_03_Numpy/Presentacion/img/M1_CLASE_03_numpyArray_vs_pythonList.png" align="center" width=80% />


### Vectorización (cont.)

---

Las operaciones vectorizadas trabajan sobre los **datos como un bloque**.  

Es necesario que los tipos sean **homogéneos** entre todos los elementos. 

En una operación vectorizada, no recorremos los elementos en orden. 

<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M1/CLASE_03_Numpy/Presentacion/img/M1_CLASE_03_computacion_vectorial.jpg" align="center" width=80% />


### Broadcasting

---

Numpy tiene un conjunto de reglas para aplicar operaciones miembro a miembro en Arrays de diferente tamaño. 

Se **proyectan** los valores de los arrays para poder operar sobre los mismos.

<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M1/CLASE_03_Numpy/Presentacion/img/M1_CLASE_03_broadcasting.jpg" align="center" width=70% />

### Broadcasting (cont.)

---

El broadcasting en NumPy sigue un conjunto estricto de reglas para determinar la interacción entre las dos arrays:

**Regla 1:**

Si los dos arrays difieren en su número de dimensiones, la forma de la que tiene menos dimensiones se rellena con unos en su lado delantero (izquierdo).

**Regla 2:**

Si la forma de los dos arrays no coincide en alguna dimensión, el array  con forma igual a 1 en esa dimensión se estira para que coincida con la otra.

**Regla 3:**

Si en alguna dimensión los tamaños son diferentes y ninguno es igual a 1, se genera un error.



<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M1/CLASE_03_Numpy/Presentacion/img/M1_CLASE_03_broadcasting_linea1.png" align="center" width=60% />
---

In [19]:
# linea 1 de la imagen:

a = np.array([0, 1, 2])
b = 5
a + b

array([5, 6, 7])

<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M1/CLASE_03_Numpy/Presentacion/img/M1_CLASE_03_broadcasting_linea2.png" align="center" width=60% />
---

In [20]:
# linea 2 de la imagen:
a = np.ones((3, 3))
b = np.array([0, 1, 2])
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M1/CLASE_03_Numpy/Presentacion/img/M1_CLASE_03_broadcasting_linea3.png" align="center" width=60% />
---

In [21]:
# linea 3 de la imagen:

a = np.array([[0], [1], [2]])
print('\na.shape:', a.shape)
print('a:')
print(a)

b = np.array([0, 1, 2])
print('\nb.shape:', b.shape)
print('b:')
print(b)

print('\na+b:')
a+b



a.shape: (3, 1)
a:
[[0]
 [1]
 [2]]

b.shape: (3,)
b:
[0 1 2]

a+b:


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

<div class="div-dhds-fondo-1"> Hands-on
<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M1/CLASE_03_Numpy/Presentacion/img/M1_CLASE_03_separador.png" align="center"></img>    
</div>


### Ejercicio 1

Dada la instancia de NumPy array

<code>data = np.array([[0, 1, 2, 3, 4], 
              [2, 3, 5, 6, 7], 
              [5, 6, 7, 8, 9], 
              [10, 11, 12, 13, 14], 
              [15, 16, 17, 18, 19], 
              [1, 2, 3, 4, 5]
             ])</code>

Obtener un array que tenga sólo las filas impares de 'data' usando:

* Slicing: 

* Fancy indexing

El resultado debe ser 

<code>np.array([[0, 1, 2, 3, 4], 
    [5, 6, 7, 8, 9], 
    [15, 16, 17, 18, 19]])</code>
                         


### Ejercicio 2

Seleccionar los elementos de valor par de 'data' usando boolean indexing


### Solución

---

In [22]:
import numpy as np
data = np.array([[0, 1, 2, 3, 4], 
              [2, 3, 5, 6, 7], 
              [5, 6, 7, 8, 9], 
              [10, 11, 12, 13, 14], 
              [15, 16, 17, 18, 19], 
              [1, 2, 3, 4, 5]
             ])
data

array([[ 0,  1,  2,  3,  4],
       [ 2,  3,  5,  6,  7],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 1,  2,  3,  4,  5]])

In [23]:
# Slicing

start = 0
stop = data.shape[1]
step = 2
data[start:stop:step, :]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [24]:
# Fancy indexing

lista_indices = [i for i in range(data.shape[1]) if i%2 == 0]
data[lista_indices, :]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [25]:
# Boolean indexing

mask = data % 2 == 0
data[mask]

array([ 0,  2,  4,  2,  6,  6,  8, 10, 12, 14, 16, 18,  2,  4])

<div class="div-dhds-fondo-1"> Referencias
<img src="https://raw.githubusercontent.com/Digital-House-DATA/ds_blend_2021_img/master/M1/CLASE_03_Numpy/Presentacion/img/M1_CLASE_03_separador.png" align="center"></img>    
</div>


### Referencias

---

<a href="https://numpy.org/" target="_blank">NumPy</a>

<a href="https://numpy.org/doc/stable/" target="_blank">Documentación</a>

<a href="https://numpy.org/learn/" target="_blank">Recursos para aprender NumPy</a>

